### ISSUE TITLE
Set assignees on review submit

### ISSUE THREAD

**Issue by ebramirez** [hkusu/review-assign-action#15]
Hi,

I don't know if it is possible, but having the possibility to set the person who created the PR as the assignee when a review is summited would be amazing.

An example setup would be:

```yaml
on:
  pull_request_review:
    types: [submitted]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.event.pull_request.user.login }}
```

**Comment by hkusu** [comment]
Currently it is not possible, because this Action can only set the assignee when the pull request is opened.

I think you can use the GitHub CLI to do something like:

```yaml
- run: gh pr edit ${{ github.event.number }} --add-assignee ${{ github.event.pull_request.user.login }} --repo ${{ github.repository }}
  env:
    GITHUB_TOKEN: ${{ github.token }}
```
