### ISSUE TITLE
Question: how to set the reviewers as assignees?

### ISSUE THREAD

**Issue by ebramirez** [hkusu/review-assign-action#16]
Is it possible to reuse the current PR reviewers value as the assignees of an Action run?

The use case would be when the author of the PR pushes more commits as a result of a review, the assignment returns to the reviewers. Example:

```yaml
on:
  pull_request:
    types: [synchronized]

jobs:
  assign:
    runs-on: ubuntu-latest
    steps:
      - uses: hkusu/review-assign-action@v1
        with:
          assignees: ${{ github.event.pull_request.reviewers ??? }}
```
