### ISSUE TITLE
Question:  how to set github team as reviewers?

### ISSUE THREAD

**Issue by valdmirGTL** [hkusu/review-assign-action#29]
Is it possible to add reviewers section with github-team?
the use case is if our team significantly change overtime, so we will need to change every our github action every time we have add new or remove new member.

for example:
```yaml
on:
  pull_request:
    types: [synchronized]
jobs:
    assign:
      runs-on: ubuntu-latest
      steps:
        - uses: hkusu/review-assign-action@v1
          with:
            reviewers: my-office-org/my-team
```
